services:
  - type: web
    name: sambus-demo-portal
    env: node
    buildCommand: bun install
    startCommand: node server.js & bun run preview --host --port 3000
    envVars:
      - key: PORT
        value: 3000
    autoDeploy: true
